# Generated by Django 5.1.4 on 2024-12-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfinance', '0007_alter_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
